### ISSUE TITLE
Demo doesn't work on safari

### ISSUE THREAD

**Issue by sbdchd** [BosNaufal/vue2-loading-bar#5]
The demo website isn't working on Safari Version 10.0.1 (10602.2.14.0.7).

<img width="950" alt="screenshot 2017-01-12 02 06 56" src="https://cloud.githubusercontent.com/assets/7340772/21880248/dbd20eda-d86b-11e6-8c75-ce4245c87132.png">

Looks great on chrome though!

**Comment by BosNaufal** [comment]
Hey @sbdchd, Thanks for making me notice about this issue~

Now it should work fine. https://github.com/BosNaufal/vue2-loading-bar/commit/6bed50fb531f5edd55633e3168f810f905ee1c39 Please Check It out again~

**Comment by sbdchd** [comment]
Perfect! Thanks!
